Args = --enable-native-access=ALL-UNNAMED \
       -H:+ReportExceptionStackTraces \
       --initialize-at-run-time=dev.mproctor.cccli.bridge.gen \
       --initialize-at-run-time=dev.mproctor.cccli.pty.PosixLibrary \
       -H:NativeLinkerOption=-rpath \
       -H:NativeLinkerOption=@executable_path/../Frameworks
